name: snowvision

channels:
  - conda-forge

dependencies:
  - python=3.11

  - pip

  - pip:
      - snowflake-snowpark-python
      - snowflake-connector-python
      - opencv-python-headless
      - numpy
      - pandas
      - pillow
      - easyocr
      - streamlit
      - networkx
      - python-dotenv
      - loguru